### ISSUE TITLE
can't find zips collection in irb

### ISSUE THREAD

**Issue by kouess6** [jhu-ep-coursera/fullstack-course3-module1#3]
Hi,
Can someone help me? I have an issue with irb to find the zips collection in irb console.
First of all, I can't use the default port 27017, so I use the 27018.
 $mongod --port 27018    ==> OK
2017-04-11T09:09:10.550+0200 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2017-04-11T09:09:10.551+0200 I NETWORK  [thread1] waiting for connections on port 27018

In another prompt,
$mongoimport --db test --collection zips --drop --file /home/kpaz/big_d/zips.json  ==> OK
2017-04-11T08:40:54.113+0200	connected to: localhost
2017-04-11T08:40:54.114+0200	dropping: test.zips
2017-04-11T08:40:54.889+0200	imported 29353 documents

$mongo
 db
test
> db.use('test')
2017-04-11T09:10:33.195+0200 E QUERY    [thread1] TypeError: db.use is not a function :
@(shell):1:1
> use test
switched to db test
> db.zips.findOne()
{
	"_id" : "01001",
	"city" : "AGAWAM",
	"loc" : [
		-72.622739,
		42.070206
	],
	"pop" : 15338,
	"state" : "MA"
}

$ irb
irb(main):001:0> require 'mongo'; Mongo::Logger.logger.level = ::Logger::INFO

=> 1
db = Mongo::Client.new('mongodb://localhost:27018')
=> #<Mongo::Client:0x47405484761380 cluster=localhost:27018>
irb(main):007:0> db=db.use('test')
=> #<Mongo::Client:0x47405485232900 cluster=localhost:27018>
irb(main):008:0> db.database.name
=> "test"
irb(main):009:0> db.database.collections
=> []
irb(main):010:0> db.database.collection_names
=> []
irb(main):011:0> 

So as you can see I don't get the zips collection in irb console, but I have it in mongo console. 
And I'm really connected to the server.

**Comment by Natalja-Olefire** [comment]
Hi, did you change the port number in your mongoid.yml file? Application (and rails console) loads DB connection information from this file, and I believe it contains "localhost:27017" by default.

**Comment by Natalja-Olefire** [comment]
Closed, is not a bug.
